### ISSUE TITLE
Using multiple grunt tasks at start of project setup

### ISSUE THREAD

**Issue by ashleynolan** [tmwagency/kickoff#47]
I’ve found it a little tricky in terms of when starting a project and using the styleguide along-side the setup docs and statix build (when using the generator).

For example, if I run grunt start, and then immediately try and run grunt styleguide, it cannot serve up the styleguide via grunt-connect because the ports it requires to do so are already in use by the earlier started grunt connect task.

We just need to tweak this so that it is possible to run these tasks simultaneously when working on a project, without having to edit the grunt configs to allow for this.

**Comment by mrmartineau** [comment]
I am adding this here as we have already discussed this matter. Styleguide sass compilation will be added to the existing `grunt watch` task so that whenever any project styles are changed, the styleguide is updated too – this would slow down compilation and style updates (when using browserSync or LiveReload) but at least it would always keep the styleguide up-to-date.

Running `grunt start` is used to install bower deps and show the project info/getting started page. I like this but as my preferred usage of the framework is using the Yeoman generator, I am not sure it is needed - Yeoman install npm and bower deps.

The idea is that users run `grunt start` at the beginning of the project, and `grunt serve` every time after that..

**Comment by mrmartineau** [comment]
FYI in Kickoff v5.0.0 you will need to run `npm run kickoff` which installs npm dependencies & shows the checklist at http://trykickoff.github.io/learn/checklist.html
